FROM python:3.10

WORKDIR /app

RUN pip install pika
RUN curl -o /usr/local/bin/wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && \
    chmod +x /usr/local/bin/wait-for-it.sh

COPY receive.py .

CMD ["python", "./receive.py"]
